# Generated by Django 2.2.2 on 2019-07-03 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodlocation',
            name='fmnp',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='foodlocation',
            name='fresh_produce',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='foodlocation',
            name='snap',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='foodlocation',
            name='wic',
            field=models.BooleanField(null=True),
        ),
    ]
