# Generated by Django 2.2.2 on 2019-07-03 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0003_auto_20190703_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodlocation',
            name='fmnp',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='foodlocation',
            name='food_bucks',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='foodlocation',
            name='fresh_produce',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='foodlocation',
            name='mrfei_score',
            field=models.IntegerField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='foodlocation',
            name='snap',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='foodlocation',
            name='wic',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
