# Generated by Django 2.2.2 on 2019-07-03 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0004_auto_20190703_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodlocation',
            name='address',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='foodlocation',
            name='city',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='foodlocation',
            name='state',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='foodlocation',
            name='street_one',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='foodlocation',
            name='street_two',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='foodlocation',
            name='zip_code',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
