# Generated by Django 2.2.2 on 2019-07-03 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0005_auto_20190703_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodlocation',
            name='location_description',
            field=models.TextField(null=True),
        ),
    ]
