# Generated by Django 2.2.2 on 2019-07-03 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0006_auto_20190703_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodlocation',
            name='latitude',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='foodlocation',
            name='longitude',
            field=models.BooleanField(null=True),
        ),
    ]
