# Generated by Django 2.2.2 on 2019-07-03 15:59

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0007_auto_20190703_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodlocation',
            name='point',
            field=django.contrib.gis.db.models.fields.PointField(null=True, srid=4326),
        ),
    ]
